### ISSUE TITLE
BlockActors & VoteActors Implementation

### ISSUE THREAD

**Issue by 4NNNN** [matter-labs/era-consensus#104]
### 🌟 Feature Request
If the implementation follows the Actor-based Model for Concurrent Byzantine Fault-tolerant Algorithm, but the leader selection/ master node selection is inspired by Hotshot. Will the block verification actors as well as voteset actors be implemented?

#### 📝 Description
In that case, would like some overview on the implementation progress and direction, would be really helpful for contributions from my side.

**Comment by brunoffranca** [comment]
No, we will not be implementing those actors.
